### ISSUE TITLE
Vulnerability (stack trace disclosure)

### ISSUE THREAD

**Issue by backcopy** [litecoin-project/insight-lite-api#26]
Sending a POST request to a number of different API endpoints is incorrectly dumping the stack trace, this information might help an attacker gain more information and potentially focus on the development of further attacks for the target system or leverage the incorrect error handling to create a new attack. 

**Example** - 

1. HTTP POST request to (https://insight.litecore.io/api/block/) with the body -  

```
{
,
}
```

This will return the following HTTP reply - 

```
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>SyntaxError: Unexpected token ,
            <br> &nbsp; &nbsp;at Object.parse (native)
            <br> &nbsp; &nbsp;at parse (/home/livenet/livenet/node_modules/litecore-node/node_modules/body-parser/lib/types/json.js:89:19)
            <br> &nbsp; &nbsp;at /home/livenet/livenet/node_modules/litecore-node/node_modules/body-parser/lib/read.js:121:18
            <br> &nbsp; &nbsp;at invokeCallback (/home/livenet/livenet/node_modules/litecore-node/node_modules/body-parser/node_modules/raw-body/index.js:224:16)
            <br> &nbsp; &nbsp;at done (/home/livenet/livenet/node_modules/litecore-node/node_modules/body-parser/node_modules/raw-body/index.js:213:7)
            <br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/livenet/livenet/node_modules/litecore-node/node_modules/body-parser/node_modules/raw-body/index.js:273:7)
            <br> &nbsp; &nbsp;at emitNone (events.js:67:13)
            <br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:166:7)
            <br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:923:12)
            <br> &nbsp; &nbsp;at nextTickCallbackWith2Args (node.js:511:9)
        </pre>
    </body>
</html>
```

There's also more stack trace dumping in other errors, see PayloadTooLargeError for eg - 

```
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>PayloadTooLargeError: request entity too large
            <br> &nbsp; &nbsp;at readStream (/home/livenet/livenet/node_modules/litecore-node/node_modules/body-parser/node_modules/raw-body/index.js:155:17)
            <br> &nbsp; &nbsp;at getRawBody (/home/livenet/livenet/node_modules/litecore-node/node_modules/body-parser/node_modules/raw-body/index.js:108:12)
            <br> &nbsp; &nbsp;at read (/home/livenet/livenet/node_modules/litecore-node/node_modules/body-parser/lib/read.js:77:3)
            <br> &nbsp; &nbsp;at jsonParser (/home/livenet/livenet/node_modules/litecore-node/node_modules/body-parser/lib/types/json.js:134:5)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/livenet/livenet/node_modules/litecore-node/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at trim_prefix (/home/livenet/livenet/node_modules/litecore-node/node_modules/express/lib/router/index.js:317:13)
            <br> &nbsp; &nbsp;at /home/livenet/livenet/node_modules/litecore-node/node_modules/express/lib/router/index.js:284:7
            <br> &nbsp; &nbsp;at Function.process_params (/home/livenet/livenet/node_modules/litecore-node/node_modules/express/lib/router/index.js:335:12)
            <br> &nbsp; &nbsp;at next (/home/livenet/livenet/node_modules/litecore-node/node_modules/express/lib/router/index.js:275:10)
            <br> &nbsp; &nbsp;at expressInit (/home/livenet/livenet/node_modules/litecore-node/node_modules/express/lib/middleware/init.js:40:5)
        </pre>
    </body>
</html>
```

**Fix** - 

1. Try catch when parsing json and handle properly or hook eventemitter and handle properly.

**Comment by iamkubi** [comment]
This is a result of the NPM environment.  To disable stack traces add an environment variable:
NODE_ENV=production

This changes the result of invalid posts to:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Bad Request</pre>
</body>
</html>
```

**Comment by krisives** [comment]
It probably should be production by default and use a switch/variable to enable debugging.

**Comment by iamkubi** [comment]
That's a matter of opinion.  I'm not a Node developer, but I do know that this is a well defined practice for Node development.  As I mentioned in the commit message, this is the officially documented way of disabling stack traces for Express:
https://expressjs.com/en/advanced/best-practice-performance.html#set-node_env-to-production

Whether you want your application settings to default to settings for a development environment or a production environment is really a matter of personal preference.  My opinion on the fix for insight-lite-api is that it should follow best practices.  In the case of Node that means defaulting to development and explicitly setting your production environments to production.

**Comment by backcopy** [comment]
Is setting NODE_ENV in lite-insight-api appropriate?

My understanding is that lite-insight-api is only an additional service to litecore-node, wouldn't litecore-node be the right place to set NODE_ENV to production? Assuming we set NODE_ENV to production on litecore-node is the stack trace still present or is NODE_ENV appropriately set on insight-lite-api too?

**Comment by iamkubi** [comment]
I put this in the setup instructions for insight-lite-api because that's what the issue was referring to.  I do agree that it makes sense to also have this documentation in litecore-node.

The documentation is still relevant here because the setup instructions on this page install litecore-node for you.  Although this service has a dependency on litecore-node it's possible to install insight-lite-api without reading any of the litecore-node documentation.

I'll also update the litecore-node README with this step.

**Comment by backcopy** [comment]
Good fix, @iamkubi 

Closing now.
